// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAWivBIDOTFn7dAYed8NZDPeQ_OSvTu8I',
    appId: '1:391362618010:web:5d56fe6ebc89a9c5dbf523',
    messagingSenderId: '391362618010',
    projectId: 'grow-logistix',
    authDomain: 'grow-logistix.firebaseapp.com',
    storageBucket: 'grow-logistix.firebasestorage.app',
    measurementId: 'G-YW3F4RVWT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAj1Lgk_6ZrFqaCEkHxEKlxYIPjHjlh5M',
    appId: '1:391362618010:android:1c9d392f0e395f16dbf523',
    messagingSenderId: '391362618010',
    projectId: 'grow-logistix',
    storageBucket: 'grow-logistix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1YB-DuqF_ymqdLgFVIpdd4jupJfidjPk',
    appId: '1:391362618010:ios:61b496d799951d7cdbf523',
    messagingSenderId: '391362618010',
    projectId: 'grow-logistix',
    storageBucket: 'grow-logistix.firebasestorage.app',
    iosBundleId: 'com.example.grow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1YB-DuqF_ymqdLgFVIpdd4jupJfidjPk',
    appId: '1:391362618010:ios:61b496d799951d7cdbf523',
    messagingSenderId: '391362618010',
    projectId: 'grow-logistix',
    storageBucket: 'grow-logistix.firebasestorage.app',
    iosBundleId: 'com.example.grow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAWivBIDOTFn7dAYed8NZDPeQ_OSvTu8I',
    appId: '1:391362618010:web:0748b69dc6501c28dbf523',
    messagingSenderId: '391362618010',
    projectId: 'grow-logistix',
    authDomain: 'grow-logistix.firebaseapp.com',
    storageBucket: 'grow-logistix.firebasestorage.app',
    measurementId: 'G-26VXPZ96W5',
  );
}
